# syntax=docker/dockerfile:1

# ---------- Stage 1: build the Vite app ----------
FROM node:22-alpine AS build
WORKDIR /app

# Install dependencies first for better layer caching.
COPY package.json package-lock.json ./
RUN npm ci

# Build the production bundle.
COPY . .
# Build-time config (override with --build-arg).
ARG VITE_API_URL=https://api.saomiguelbus.com
ARG VITE_ISLAND_KEY=sao-miguel
ARG VITE_SITE_URL=https://app.saomiguelbus.com
ARG VITE_BASE_DOMAIN=saomiguelbus.com
ARG VITE_ANDROID_APP_URL=
ARG VITE_IOS_APP_URL=https://apps.apple.com/app/id6777066837
ARG VITE_IOS_APP_ID=6777066837
# Display ads (see .env.example). Defaults serve the Adsterra Native Banner placements; set
# VITE_WEB_AD_PROVIDERS=adsense,adsterra once the AdSense site review passes.
ARG VITE_WEB_AD_PROVIDERS=adsterra
ARG VITE_ADSENSE_CLIENT=ca-pub-8246676797736648
ARG VITE_ADSENSE_SLOT_TOP=
ARG VITE_ADSENSE_SLOT_INLINE=
ARG VITE_ADSENSE_SLOT_SIDEBAR=
ARG VITE_ADSENSE_SLOT_FOOTER=
ARG VITE_ADSENSE_TEST=
ARG VITE_ADSTERRA_NATIVE_TOP=https://pl31201609.profitableratecpmnetwork.com/5fbee8732f91268c27456a638205eeee/invoke.js
ARG VITE_ADSTERRA_NATIVE_INLINE=https://pl31201609.profitableratecpmnetwork.com/5fbee8732f91268c27456a638205eeee/invoke.js
ARG VITE_ADSTERRA_NATIVE_SIDEBAR=
ARG VITE_ADSTERRA_NATIVE_FOOTER=
ARG VITE_ADSTERRA_FRAME_HEIGHT=
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_ISLAND_KEY=$VITE_ISLAND_KEY
ENV VITE_SITE_URL=$VITE_SITE_URL
ENV VITE_BASE_DOMAIN=$VITE_BASE_DOMAIN
ENV VITE_ANDROID_APP_URL=$VITE_ANDROID_APP_URL
ENV VITE_IOS_APP_URL=$VITE_IOS_APP_URL
ENV VITE_IOS_APP_ID=$VITE_IOS_APP_ID
ENV VITE_WEB_AD_PROVIDERS=$VITE_WEB_AD_PROVIDERS
ENV VITE_ADSENSE_CLIENT=$VITE_ADSENSE_CLIENT
ENV VITE_ADSENSE_SLOT_TOP=$VITE_ADSENSE_SLOT_TOP
ENV VITE_ADSENSE_SLOT_INLINE=$VITE_ADSENSE_SLOT_INLINE
ENV VITE_ADSENSE_SLOT_SIDEBAR=$VITE_ADSENSE_SLOT_SIDEBAR
ENV VITE_ADSENSE_SLOT_FOOTER=$VITE_ADSENSE_SLOT_FOOTER
ENV VITE_ADSENSE_TEST=$VITE_ADSENSE_TEST
ENV VITE_ADSTERRA_NATIVE_TOP=$VITE_ADSTERRA_NATIVE_TOP
ENV VITE_ADSTERRA_NATIVE_INLINE=$VITE_ADSTERRA_NATIVE_INLINE
ENV VITE_ADSTERRA_NATIVE_SIDEBAR=$VITE_ADSTERRA_NATIVE_SIDEBAR
ENV VITE_ADSTERRA_NATIVE_FOOTER=$VITE_ADSTERRA_NATIVE_FOOTER
ENV VITE_ADSTERRA_FRAME_HEIGHT=$VITE_ADSTERRA_FRAME_HEIGHT
RUN npm run build

# ---------- Stage 2: serve static files with nginx ----------
FROM nginx:1.27-alpine AS runtime
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
