/**
 * Village-level ("area") grouping — the TS mirror of
 * `azoresbus/services_stops.py`'s `derive_area_key`/`build_area_index` on the
 * API repo. Same rule, same numbers, pinned against the SAME real fixture
 * (`test/fixtures/azoresbus/stops.canonical.json`, generated by the API's
 * `manage.py dump_canonical_stops` and copied byte-identically here and to
 * the Expo app — never re-captured, never fetched), so three implementations
 * of one string-normalisation rule cannot silently disagree without a test
 * noticing on every side.
 *
 * The CANONICAL fixture, not the raw one, because that is what `Stop.name`
 * holds. The API canonicalizes upstream's inconsistent spellings at import
 * (`P. DELGADA` / `PONTA DELGADA` were two villages to this rule, so
 * "Ponta Delgada" found 3 stops out of 38). Testing the raw names here would
 * leave these assertions green while pinning a name domain production no
 * longer serves.
 *
 * A different axis from the pole-collapse the backend does at import time
 * (1456 poles → 814 `Stop` rows by canonical name) — this groups those
 * already-collapsed 814 names by a shared VILLAGE PREFIX, for search only. It
 * never merges two real stops into one.
 */

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';

import { deriveAreaKey, findAreaByQuery, groupStopsIntoAreas } from '@/lib/stop-areas';

interface UpstreamStop {
  id: string;
  name: string;
}

function realStopNames(): string[] {
  const raw = JSON.parse(
    readFileSync(
      join(process.cwd(), 'test', 'fixtures', 'azoresbus', 'stops.canonical.json'),
      'utf8',
    ),
  ) as UpstreamStop[];
  return [...new Set(raw.map((row) => row.name))].sort();
}

function stopsFrom(names: string[]): { id: number; name: string }[] {
  return names.map((name, index) => ({ id: index + 1, name }));
}

describe('deriveAreaKey', () => {
  it('splits on the first " ("', () => {
    expect(deriveAreaKey('CAPELAS (IGREJA)')).toBe('CAPELAS');
  });

  it('returns null for a bare name with no parens', () => {
    expect(deriveAreaKey('ACHADINHA')).toBeNull();
  });

  it('groups a trailing pole number after the closing paren', () => {
    // Splitting on the FIRST " (" rather than requiring the string to end in
    // ")" is what catches this.
    expect(deriveAreaKey('ARRIFES (LG. DO BOM DESPACHO) 1')).toBe('ARRIFES');
    expect(deriveAreaKey('ARRIFES (LG. DO BOM DESPACHO) 2')).toBe('ARRIFES');
  });

  it('trims whitespace before the paren', () => {
    expect(deriveAreaKey('CAPELAS  (IGREJA)')).toBe('CAPELAS');
  });
});

describe('groupStopsIntoAreas — real data, pinned against the shared fixture', () => {
  const names = realStopNames();
  const stops = stopsFrom(names);
  const areas = groupStopsIntoAreas(stops);

  it("matches the backend's real counts: 814 names, 79 areas, 778 covered", () => {
    expect(names.length).toBe(814);
    expect(areas.size).toBe(79);
    const covered = [...areas.values()].reduce((sum, members) => sum + members.length, 0);
    expect(covered).toBe(778);
  });

  it('Capelas has 37 members', () => {
    expect(areas.get('Capelas')?.length).toBe(37);
  });

  it('spelling variants no longer split a village', () => {
    // The whole reason canonicalization exists. Before it, `P. DELGADA` and
    // `PONTA DELGADA` were separate keys so "Ponta Delgada" resolved to 3
    // stops out of 38; `SÃO VICENTE FERREIRA` had 29 stops and NO key at all,
    // because each of its two spellings looked like a sub-2-member singleton.
    expect(areas.get('Ponta Delgada')?.length).toBe(38);
    expect(areas.get('São Vicente Ferreira')?.length).toBe(29);
    expect(areas.get('São Roque')?.length).toBe(17);
    expect(areas.get('Vila do Nordeste')?.length).toBe(12);
    for (const retired of ['P. DELGADA', 'V. DO NORDESTE', 'S. ROQUE', 'NORDESTE']) {
      expect(areas.has(retired), retired).toBe(false);
    }
  });

  it('keeps the two Santa Bárbaras apart', () => {
    // A blind `STA.` → `Santa` rewrite would union two villages 16.5 km
    // apart. The API's code-scoped override splits them; this pins that the
    // split survives the trip through the fixture.
    expect(areas.get('Santa Bárbara da Ribeira Grande')?.length).toBe(11);
    expect(areas.has('Santa Bárbara')).toBe(true);
    expect(areas.has('STA. BÁRBARA')).toBe(false);
  });

  it('numbered variants rejoin their village without merging', () => {
    // `LOMBA DO BOTÃO 1/2/3` are three real stops up to a km apart. They were
    // three 1-member keys, so all three were dropped; parenthesising the
    // discriminator puts them in the village while keeping them distinct.
    expect(areas.get('Lomba do Botão')?.length).toBe(9);
  });

  it('the largest area is Arrifes with 47', () => {
    const [largestKey, largest] = [...areas.entries()].reduce((best, entry) =>
      entry[1].length > best[1].length ? entry : best,
    );
    expect(largestKey).toBe('Arrifes');
    expect(largest.length).toBe(47);
  });

  it('single-member "areas" are excluded — no grouping benefit', () => {
    expect(areas.has('Achadinha')).toBe(false);
    expect(areas.has('Algarvia')).toBe(false);
  });

  it('collision-excluded areas are absent', () => {
    for (const excluded of ['Aflitos', 'Várzea', 'Achadinha', 'Algarvia', 'Ribeira Funda']) {
      expect(areas.has(excluded), excluded).toBe(false);
    }
  });

  it('every member actually belongs under its key', () => {
    for (const [key, members] of areas) {
      for (const member of members) {
        expect(deriveAreaKey(member.name), member.name).toBe(key);
      }
    }
  });

  it('is stable across input order', () => {
    const reversed = groupStopsIntoAreas([...stops].reverse());
    expect([...areas.keys()].sort()).toEqual([...reversed.keys()].sort());
    for (const key of areas.keys()) {
      expect(areas.get(key)!.length, key).toBe(reversed.get(key)!.length);
    }
  });
});

describe('groupStopsIntoAreas — collision exclusion, isolated fixtures', () => {
  it('a bare stop blocks its own area key', () => {
    const areas = groupStopsIntoAreas(
      stopsFrom(['AFLITOS', 'AFLITOS (ESCOLA)', 'AFLITOS (IGREJA)']),
    );
    expect(areas.has('AFLITOS')).toBe(false);
  });

  it('the exclusion is accent- and case-folded (foldStopName, not a bare match)', () => {
    const areas = groupStopsIntoAreas(
      stopsFrom(['Água Retorta', 'AGUA RETORTA (PORTO)', 'AGUA RETORTA (PRAIA)']),
    );
    expect(areas.size).toBe(0);
  });

  it('without a colliding bare stop, the area forms normally', () => {
    const areas = groupStopsIntoAreas(stopsFrom(['CAPELAS (IGREJA)', 'CAPELAS (MOAGEM)']));
    expect(areas.get('CAPELAS')?.length).toBe(2);
  });

  it('a single matching stop never forms an area', () => {
    const areas = groupStopsIntoAreas(stopsFrom(['CAPELAS (IGREJA)', 'ARRIFES (ESCOLA)']));
    expect(areas.size).toBe(0);
  });

  it('is generic over any stop-like shape', () => {
    const areas = groupStopsIntoAreas([
      { id: 1, name: 'CAPELAS (IGREJA)', latitude: 0, longitude: 0 },
      { id: 2, name: 'CAPELAS (MOAGEM)', latitude: 0, longitude: 0 },
    ]);
    expect(areas.get('CAPELAS')?.length).toBe(2);
  });
});

describe('findAreaByQuery — the folded lookup', () => {
  const areas = groupStopsIntoAreas(
    stopsFrom(['CAPELAS (IGREJA)', 'CAPELAS (MOAGEM)', 'ARRIFES (ESCOLA)', 'ARRIFES (IGREJA)']),
  );

  it('matches a lowercase, unaccented query against an uppercase key', () => {
    expect(findAreaByQuery(areas, 'capelas')?.length).toBe(2);
  });

  it('matches an accented query against an unaccented key and vice versa', () => {
    const withAccent = groupStopsIntoAreas(
      stopsFrom(['SÃO ROQUE (IGREJA)', 'SÃO ROQUE (ESCOLA)']),
    );
    expect(findAreaByQuery(withAccent, 'sao roque')?.length).toBe(2);
    expect(findAreaByQuery(withAccent, 'São Roque')?.length).toBe(2);
  });

  it('returns null for a query matching no area', () => {
    expect(findAreaByQuery(areas, 'zzzz')).toBeNull();
  });

  it('returns null for a query matching a member but not the area itself', () => {
    // "Igreja" is a landmark shared by multiple villages, not an area key.
    expect(findAreaByQuery(areas, 'igreja')).toBeNull();
  });
});
